dist: xenial
language: rust
os: linux
rust:
  - nightly
  - beta
  - stable
  - 1.40.0
env:
  - GTK=3.14 FEATURES=
  - GTK=3.24 FEATURES=v3_18

addons:
  apt:
    packages:
    - libgtk-3-dev
    - libgtksourceview-3.0-dev
    - libmount-dev

script:
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ] && [ "$GTK" == "3.14" ]; then
      rustup component add rustfmt;
      make regen_check;
    fi
  - ./check_init_asserts
  - cargo doc --features "dox,embed-lgpl-docs"
  - cargo test --features "$FEATURES,embed-lgpl-docs"
  # catch any sneaked in lgpl docs
  - cargo build --features "$FEATURES,purge-lgpl-docs" --jobs 1
  - git diff -R --exit-code
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 -b pending https://github.com/gtk-rs/examples _examples
  - cd _examples
  - ./build_travis.sh
  - if [ "$TRAVIS_RUST_VERSION" == "stable" ] && [ "$GTK" == "3.14" ]; then
      cd ..;
      git clone https://github.com/gtk-rs/checker;
      cd checker && cargo build --release;
      cd .. && ./checker/target/release/checker .;
    fi
